### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by turpedogamer** [yPedx/SB-GUI#17]
I was just reloading my plugin using /sb reload then this happened
Console Error: https://pastebin.com/i5VRCPqz

Config: https://pastebin.com/Rfppd0Ed

**Comment by yPedx** [comment]
Replace your "Configurations"section with this:

```
Configurations: 
  Stats-Item: SIGN 
  Next-Page-Item: BOOK 
  Options-Item: NETHER_STAR
```

And change the values to your likings.
